Repository microsoft/vscode-pylint, pull requests merged in 2022-06, with the labels that each got.

#108 Update packages
  package-lock.json
  package.json
Labels: debt, skip news

#110 Fix bug when trying to show diagnostics
  bundled/linter/linter_server.py
Labels: bug, skip news

#111 Update pylint
  README.md
  bundled/linter/utils.py
  noxfile.py
  requirements.txt
Labels: debt, news

#112 Improve output parsing and error reporting.
  bundled/linter/linter_server.py
Labels: debt, skip news

#113 Set preview flag on the extension.
  package.json
Labels: debt, skip news

#114 Update packages
  package-lock.json
  package.json
Labels: debt, skip news

#118 Update pylint
  README.md
  package-lock.json
  package.json
  requirements.txt
Labels: debt, news

#120 Update main for preview release.
  CHANGELOG.md
  NOTICE.txt
  package-lock.json
  package.json
Labels: debt, skip news

#121 Update main version for next pre-release.
  package-lock.json
  package.json
Labels: debt, skip news

#103 Handle multi-python scenario using subprocess.
  .github/dependabot.yml
  bundled/linter/jsonrpc.py
  bundled/linter/linter_server.py
  bundled/linter/runner.py
  bundled/linter/utils.py
  package.json
  src/common/log/fileLogger.ts
  src/common/log/logging.ts
  src/common/log/outputChannelLogger.ts
  src/common/log/types.ts
  src/common/python.ts
  src/common/server.ts
  src/common/settings.ts
  src/common/setup.ts
  src/extension.ts
  src/test/python_tests/lsp_test_client/defaults.py
  src/test/python_tests/lsp_test_client/utils.py
  src/test/python_tests/test_linting.py
Labels: debt, skip news

#127 Update packages.
  package-lock.json
  package.json
  requirements.txt
Labels: debt, skip news
