Repository microsoft/vscode-pylint, pull requests merged in 2022-09, with the labels that each got.

#172 Code Action fixes using existing command.
  .vscode/settings.json
  bundled/tool/server.py
  bundled/tool/utils.py
  src/test/python_tests/lsp_test_client/session.py
  src/test/python_tests/test_code_actions.py
Labels: feature-request

#186 Rollback typescript version to 4.7.4
  package-lock.json
  package.json
  requirements.txt
  src/test/python_tests/requirements.txt
Labels: bug

#188 Re-ordering settings in package.json alphabetically #183
  package.json
Labels: debt
