Repository microsoft/vscode-pylint, pull requests merged in 2022-11, with the labels that each got.

#212 Update packages and extension version
  package-lock.json
  package.json
  requirements.txt
  src/test/python_tests/requirements.txt
Labels: no-changelog

#218 Add support for quick fixes resolved by formatting or import organization
  bundled/tool/server.py
  requirements.txt
  src/test/python_tests/requirements.txt
  src/test/python_tests/test_code_actions.py
Labels: feature-request

#221 Remove PR Chat
  .github/workflows/pr-chat.yml
Labels: debt
