Repository microsoft/vscode-pylint, pull requests merged in 2022-08, with the labels that each got.

#152 Update packages.
  noxfile.py
  package-lock.json
  package.json
Labels: no-changelog

#156 Fix issue with multiroot multi python.
  bundled/tool/jsonrpc.py
  bundled/tool/runner.py
  bundled/tool/server.py
  src/test/python_tests/lsp_test_client/utils.py
  src/test/python_tests/test_path_specialization.py
Labels: bug

#159 Update version for release.
  package-lock.json
  package.json
Labels: no-changelog

#160 Update main version to next pre-release.
  package-lock.json
  package.json
Labels: no-changelog

#166 Add PR Chat
  .github/workflows/pr-chat.yml
Labels: no-changelog

#170 Update packages.
  README.md
  package-lock.json
  package.json
  requirements.txt
  src/test/python_tests/requirements.txt
Labels: debt

#171 Fix path tests.
  .pylintrc
  bundled/tool/server.py
  src/test/python_tests/lsp_test_client/utils.py
  src/test/python_tests/test_path_specialization.py
Labels: bug
