Repository microsoft/vscode-pylint, pull requests merged in 2022-10, with the labels that each got.

#197 Update Packages
  README.md
  package-lock.json
  package.json
  requirements.txt
  src/test/python_tests/requirements.txt
Labels: no-changelog

#196 Merge from GHC OSD branch.
  package.json
Labels: debt

#189 Add code action to format code when there's a "trailing newlines" warning
  bundled/tool/server.py
  src/test/python_tests/test_code_actions.py
Labels: feature-request

#198 Update to use latest python environment APIs
  package-lock.json
  package.json
  src/common/python.ts
Labels: feature-request

#201 Update CHANGELOG.md
  CHANGELOG.md
Labels: no-changelog

#202 Add support to handle legacy settings.
  .vscode/settings.json
  bundled/tool/server.py
  src/common/settings.ts
  src/common/utilities.ts
  src/extension.ts
Labels: debt

#203 Feature/trailing whitespace
  bundled/tool/server.py
  src/test/python_tests/test_code_actions.py
Labels: feature-request

#207 Fix for pydantic crash on Python 3.11
  .github/actions/lint/action.yml
  .github/workflows/pr-check.yml
  README.md
  noxfile.py
  requirements.txt
  src/test/python_tests/test_linting.py
Labels: bug

#210 Update packages.
  package-lock.json
  package.json
  requirements.txt
  src/test/python_tests/requirements.txt
Labels: no-changelog
