Repository microsoft/vscode-pylint, pull requests merged in 2023-02, with the labels that each got.

#256 Remove redundant activation events
  bundled/tool/lsp_jsonrpc.py
  bundled/tool/lsp_server.py
  noxfile.py
  package.json
Labels: debt

#264 Ensure LSP server is shutdown on extension exit
  bundled/tool/lsp_server.py
  src/extension.ts
Labels: bug

#266 Enable dependabot for custom actions
  .github/dependabot.yml
Labels: no-changelog

#265 Update packages
  README.md
  package-lock.json
  package.json
  requirements.txt
  src/test/python_tests/requirements.txt
Labels: no-changelog

#267 Use `--clear-cache-post-run` when running pylint >= 2.16 and <3
  bundled/tool/lsp_server.py
Labels: bug

#275 Update pre-release version and packages
  package-lock.json
  package.json
  requirements.txt
  src/test/python_tests/requirements.txt
Labels: no-changelog

#276 Update release version and readme.
  README.md
  package-lock.json
  package.json
Labels: no-changelog

#277 Update README.md
  README.md
Labels: no-changelog

#278 Update main version to next pre-release
  package-lock.json
  package.json
Labels: no-changelog

#284 Ensure global settings are passed to the server.
  bundled/tool/lsp_server.py
  src/common/server.ts
  src/common/settings.ts
  src/test/python_tests/lsp_test_client/utils.py
Labels: bug
