Repository microsoft/vscode-pylint, pull requests merged in 2023-11, with the labels that each got.

#430 Add more details to README and settings descriptions
  README.md
  package.json
  package.nls.json
Labels: documentation, debt

#434 Update version and packages for release
  README.md
  dev-requirements.txt
  package-lock.json
  package.json
  requirements.txt
  src/test/python_tests/requirements.txt
Labels: no-changelog

#435 Update version for pre-release
  package-lock.json
  package.json
Labels: no-changelog

#440 Update ci and build scripts
  .github/workflows/pr-check.yml
  .github/workflows/push-check.yml
  build/azure-pipeline.pre-release.yml
  build/azure-pipeline.stable.yml
Labels: debt

#447 Fix for `${fileDirname}` crash
  src/common/server.ts
Labels: bug

#452 Use fnmatch instead of pathlibs match
  bundled/tool/lsp_utils.py
Labels: bug

#449 Update glob pattern docs link
  README.md
  package.nls.json
Labels: bug, documentation

#457 Fix for code action performance issue with pylint
  bundled/tool/lsp_server.py
  src/test/python_tests/test_code_actions.py
Labels: bug
