Repository microsoft/vscode-pylint, pull requests merged in 2023-01, with the labels that each got.

#243 Use `lsprotocol` for the lsp base
  README.md
  bundled/tool/server.py
  package-lock.json
  package.json
  requirements.txt
  src/test/python_tests/requirements.txt
  src/test/python_tests/test_code_actions.py
Labels: dependencies, debt

#244 Change internal file names to avoid shadowing
  bundled/tool/_debug_server.py
  bundled/tool/lsp_jsonrpc.py
  bundled/tool/lsp_runner.py
  bundled/tool/lsp_server.py
  bundled/tool/lsp_utils.py
  src/common/constants.ts
  src/test/python_tests/lsp_test_client/session.py
Labels: bug

#248 Update localization
  .github/workflows/pr-check.yml
  build/azure-pipeline.pre-release.yml
  build/azure-pipeline.stable.yml
  package-lock.json
  package.json
  src/extension.ts
  src/setupNLS.ts
  src/test/python_tests/test_linting.py
  webpack.config.js
Labels: debt

#250 Switch to logging via VS Code logging
  README.md
  bundled/tool/lsp_server.py
  package-lock.json
  package.json
  package.nls.json
  requirements.txt
  src/common/log/fileLogger.ts
  src/common/log/logging.ts
  src/common/log/outputChannelLogger.ts
  src/common/log/types.ts
  src/common/server.ts
  src/common/settings.ts
  src/common/utilities.ts
  src/common/vscodeapi.ts
  src/extension.ts
  src/test/python_tests/requirements.txt
Labels: debt

#251 Add support for legacy `python.linting.cwd` setting
  bundled/tool/lsp_jsonrpc.py
  bundled/tool/lsp_server.py
  src/common/settings.ts
  src/test/python_tests/lsp_test_client/utils.py
Labels: feature-request

#252 Set Dependabot Python version
  runtime.txt
Labels: dependencies, debt

#254 Ensure current working dir is on `sys.path` for `pylint`.
  bundled/tool/lsp_runner.py
  bundled/tool/lsp_server.py
  src/common/server.ts
Labels: bug

#255 Add support for extra paths.
  bundled/tool/lsp_jsonrpc.py
  bundled/tool/lsp_server.py
  bundled/tool/lsp_utils.py
  src/common/settings.ts
  src/test/python_tests/lsp_test_client/utils.py
  src/test/python_tests/test_extra_paths.py
  src/test/python_tests/test_path_specialization.py
Labels: bug
