Repository microsoft/vscode-pylint, pull requests merged in 2023-03, with the labels that each got.

#285 Clean up and fixes from other extensions
  .vscodeignore
  README.md
  package-lock.json
  package.json
  requirements.txt
  src/common/log/logging.ts
  src/common/python.ts
  src/common/server.ts
  src/common/utilities.ts
  src/extension.ts
  src/test/python_tests/requirements.txt
Labels: debt

#291 Update version for release
  package-lock.json
  package.json
Labels: no-changelog

#292 Update main to next pre-release
  package-lock.json
  package.json
Labels: no-changelog

#298 Add support to open the online message documentation as quick fix action
  bundled/tool/lsp_server.py
  bundled/tool/lsp_utils.py
  src/test/python_tests/test_linting.py
Labels: feature-request

#300 Add code actions for simple Pylint items
  bundled/tool/lsp_server.py
  src/test/python_tests/test_code_actions.py
Labels: feature-request

#304 Add basic codespace configuration for development
  .devcontainer/Dockerfile
  .devcontainer/devcontainer.json
  .gitignore
  .pylintrc
  .vscode/settings.json
  dev-requirements.in
  dev-requirements.txt
  pyproject.toml
Labels: debt

#306 Update to dev container and packages
  .devcontainer/devcontainer.json
  .vscode/settings.json
  README.md
  package-lock.json
  package.json
  requirements.txt
  src/test/python_tests/requirements.txt
Labels: no-changelog

#303 Add auto-fixes for C0113, C0121, C0123
  bundled/tool/lsp_server.py
  src/test/python_tests/test_code_actions.py
Labels: feature-request
