Repository microsoft/vscode-pylint, pull requests merged in 2023-10, with the labels that each got.

#408 Update to latest version of packages and python
  .devcontainer/Dockerfile
  .github/actions/build-vsix/action.yml
  .github/actions/lint/action.yml
  .github/workflows/pr-check.yml
  .github/workflows/push-check.yml
  README.md
  build/azure-pipeline.pre-release.yml
  build/azure-pipeline.stable.yml
  bundled/tool/lsp_server.py
  dev-requirements.in
  dev-requirements.txt
  noxfile.py
  package-lock.json
  package.json
  requirements.in
  requirements.txt
  runtime.txt
  src/common/python.ts
  src/extension.ts
  src/test/python_tests/requirements.in
  src/test/python_tests/requirements.txt
  src/test/python_tests/test_code_actions.py
Labels: debt

#409 Update version for release
  package-lock.json
  package.json
Labels: no-changelog

#411 Update to latest pylint 3.0.1
  README.md
  requirements.txt
Labels: debt

#412 Update main to next pre-release version
  package-lock.json
  package.json
Labels: no-changelog

#416 Fix for caching issue
  bundled/tool/lsp_server.py
Labels: bug

#418 Remove preview tag
  package.json
Labels: no-changelog

#419 Revert "Remove preview tag (#418)"
  package.json
Labels: no-changelog

#415 Adds ignore pattern and stdlib filter settings.
  README.md
  bundled/tool/lsp_server.py
  bundled/tool/lsp_utils.py
  package.json
  package.nls.json
  src/common/settings.ts
  src/test/python_tests/lsp_test_client/defaults.py
  src/test/python_tests/lsp_test_client/session.py
  src/test/python_tests/test_extra_paths.py
  src/test/python_tests/test_linting.py
  src/test/python_tests/test_path_specialization.py
  src/test/ts_tests/tests/common/settings.unit.test.ts
Labels: feature-request

#422 Add missing linting features
  README.md
  bundled/tool/lsp_server.py
  dev-requirements.txt
  package-lock.json
  package.json
  package.nls.json
  requirements.txt
  src/common/constants.ts
  src/common/python.ts
  src/common/server.ts
  src/common/settings.ts
  src/common/status.ts
  src/common/vscodeapi.ts
  src/extension.ts
  src/test/ts_tests/tests/common/settings.unit.test.ts
Labels: feature-request

#390 Fixed capitalization of "Python" in user-facing text
  README.md
  build/update_ext_version.py
  package.nls.json
  src/common/python.ts
  src/common/server.ts
  src/test/python_tests/lsp_test_client/utils.py
Labels: debt

#423 Clean up after deprecating legacy settings
  README.md
  src/common/server.ts
  src/common/settings.ts
  src/common/utilities.ts
  src/extension.ts
  src/test/python_tests/lsp_test_client/session.py
  src/test/python_tests/test_linting.py
Labels: debt

#425 Remove stdlib setting
  README.md
  bundled/tool/lsp_server.py
  package.json
  package.nls.json
  src/common/settings.ts
  src/test/python_tests/test_linting.py
  src/test/ts_tests/tests/common/settings.unit.test.ts
Labels: no-changelog
