Repository microsoft/vscode-pylint, pull requests merged in 2023-06, with the labels that each got.

#343 Engineering - update pre-release pipeline
  build/azure-pipeline.pre-release.yml
Labels: debt

#344 Engineering - add TSAOptions
  build/azure-pipeline.stable.yml
Labels: no-changelog

#346 Mark virtual workspaces as unsupported in package.json
  package.json
Labels: bug
