Repository microsoft/vscode-pylint, pull requests merged in 2023-08, with the labels that each got.

#365 Add more settings and resolver tests
  .github/workflows/pr-check.yml
  .github/workflows/push-check.yml
  .gitignore
  .vscode/launch.json
  .vscodeignore
  package-lock.json
  package.json
  src/common/logging.ts
  src/common/python.ts
  src/common/server.ts
  src/common/settings.ts
  src/common/utilities.ts
  src/extension.ts
  src/test/ts_tests/index.ts
  src/test/ts_tests/runTest.ts
  src/test/ts_tests/tests/common/settings.unit.test.ts
  src/test/ts_tests/tests/common/utilities.unit.test.ts
  tsconfig.json
Labels: debt

#359 Update packages
  README.md
  dev-requirements.txt
  package-lock.json
  package.json
  requirements.txt
Labels: debt

#367 Ensure `tool` dir is always on path
  bundled/tool/lsp_runner.py
  bundled/tool/lsp_server.py
Labels: bug

#368 Support linting on change
  bundled/tool/lsp_server.py
  package.json
  package.nls.json
  src/common/server.ts
  src/common/settings.ts
  src/test/python_tests/test_data/sample2/sample.py
  src/test/python_tests/test_linting.py
  src/test/ts_tests/tests/common/settings.unit.test.ts
Labels: feature-request

#369 Fix tests
  src/test/python_tests/test_linting.py
Labels: no-changelog

#372 Fix lint on change setting description
  package.json
Labels: no-changelog

#373 Update readme to include `lintOnChange` setting.
  README.md
Labels: no-changelog

#371 Add more tests for on change linting
  src/test/python_tests/test_linting.py
Labels: no-changelog
