Repository microsoft/vscode-pylint, pull requests merged in 2024-03, with the labels that each got.

#526 Update packages and fix linting issues
  README.md
  dev-requirements.txt
  package-lock.json
  package.json
  requirements.txt
  src/test/python_tests/requirements.txt
  src/test/python_tests/test_extra_paths.py
  src/test/python_tests/test_path_specialization.py
Labels: debt

#524 Add logic to replace tilde with home environment
  src/common/settings.ts
  src/test/ts_tests/tests/common/settings.unit.test.ts
Labels: bug

#531 Engineering - cleanup TSA pipeline template parameter
  build/azure-pipeline.pre-release.yml
  build/azure-pipeline.stable.yml
Labels: feature-request
